### ISSUE TITLE
CPGGraph.to_torch() generated class does not return correct shape for constant functions

### ISSUE THREAD

**Issue by mschmidt87** [jakobj/python-gp#22]
When a genome represents a constant function, e.g. `f(x)=1`, the torch class generated by CPGGraph does not return the correct shape. I created a test for this on the `bugfix/torch_constant_output_shape` branch: https://github.com/jakobj/python-gp/blob/5a50c07876adf9e8a263b4e10c0e01c5b582fb68/test/test_cgp_graph.py#L161

This can probably be fixed by modifying the `CGPConstantFloat.format_output_str_torch()` method.
https://github.com/jakobj/python-gp/blob/3bdff24be10ef503652b44b0be1606a639555627/gp/cgp_node.py#L191

**Comment by mschmidt87** [comment]
I think that the constant float / torch.nn.Parameter needs to be unsqueezed and then the 0-th dimension needs to be blown up to the batch dimension. Something like this:
`self._output_str = 'torch.cat(x.shape[0] * [self._p{}.unsqueeze(0)])'.format(self._idx)`

**Comment by jakobj** [comment]
i'm not even sure what the `CGPConstantFloat.format_output_str_torch` method does, is it even used? it does not make use of the actual value of the node (`self._output`) but only of the node index to define a new member variable. maybe that function should never be called in the first place (add `raise ...`?), but only the function `format_parameter_str` that should actually be called `format_parameter_str_torch`? in this function, one could just resize the tensor to include a batch dimension, correct?

**Comment by mschmidt87** [comment]
As far as I understand, the ` CGPConstantFloat.format_output_str_torch` is called in `CGPGraph.compile_torch_class()` when the `forward` method of the torch class is written:
https://github.com/jakobj/python-gp/blob/3bdff24be10ef503652b44b0be1606a639555627/gp/cgp_graph.py#L218

This function calls `format_output_str_torch` is called on the output nodes here which call this method on their input nodes leading to a recursive call.

On the other hand, the `format_parameter_str` method is used to construct the `__init__()` method of the torch class:
https://github.com/jakobj/python-gp/blob/3bdff24be10ef503652b44b0be1606a639555627/gp/cgp_graph.py#L200

This makes sense because in the `__init__()` method, the constant float has to be defined (for example set to 1.0) and then in the forward method it is used.

**Comment by jakobj** [comment]
ah i see, thanks for explaining! who the hell wrote that code? ;)
