### ISSUE TITLE
Remove `cgp_constant_float` factory

### ISSUE THREAD

**Issue by jakobj** [jakobj/python-gp#29]
The factory seems pretty pointless (https://github.com/jakobj/python-gp/blob/master/gp/cgp_node.py#L236) and should be removed: it takes only three lines to define your own constant float node (and avoiding pickling issues):
```python
class CustomCGPConstantFloat(CGPConstantFloat):
    def __init__(self, idx, inputs):
      super().__init__(idx, inputs)
      self._output = val
```
isn't that short enough? @mschmidt87

**Comment by mschmidt87** [comment]
Actually, that's exactly what I've been doing, i.e. I never used the factory. ^^
However, it's still more convenient to use the factory, and perhaps one like to use it in a procedural way and then it would nice to just write one line instead of four.

**Comment by jakobj** [comment]
ok, maybe it's not a terrible idea. i think in that case it would be nice to move the function from the file where nodes are defined to a separate file which contains only factories such that one would use it like `MyConstFloat = gp.node_factories.ConstantFloat(0.1)`, but i'm not commited to the module name ;). what do you think?

**Comment by mschmidt87** [comment]
Yes, that sounds like a good idea.
