### ISSUE TITLE
Remove "CGP/cgp" prefixes where possible

### ISSUE THREAD

**Issue by jakobj** [jakobj/python-gp#31]
We are using a lot of unnecessary prefixes, e.g., "CGPGraph", "CGPInputNode" etc. which was i guess motivated by not only having a `CGPPopulation` but also the `BinaryPopulation` class. Since we decided to remove the latter we should also go ahead and remove these prefixes to make the code more readable and avoid typing

**Comment by mschmidt87** [comment]
Related to #5
