### ISSUE TITLE
Check whether silent mutations in nodes inputs are allowed

### ISSUE THREAD

**Issue by jakobj** [jakobj/python-gp#37]
In principle each node has the same number of input genes, independent of its currently selected operation, e.g., a node with arity=1 still has 2 input genes if the max arity in the graph is 2. Does the current implementation allow the mutation of the silent input genes or are these excluded? Since silent mutations seem to be beneficial generally, we should make sure this is the case.

**Comment by mschmidt87** [comment]
Currently, the only node with arity=1 is the OutputNode. Its silent input is the second entry which is always `None`, as far as I can see. Thus, it seems that this cannot be mutated? However, I don't quite understand the `cartesian_gaph._determine_active_nodes()` function which appears to be crucial for mutations. Can you explain this a bit more and ideally this should be written in a docstring of the function.

**Comment by jakobj** [comment]
Yes, you are right. Unused genes are currently not mutated, there are checks in `mutate` such as `if self._dna[gene_idx] is not self._non_coding_allele` that prevent this. I would suggest to remove these checks and also allow mutations in dna parts which are currently non-coding. maybe this would allow us to remove the `self._non_coding_allele` completely. @mschmidt87 what do you think?

also, i've improved the implementation of `_determine_active_nodes` this should be more clear now (#82)

**Comment by mschmidt87** [comment]
As far as I understand, the argument in favour of silent mutations is that these mutations can silently accumulate and then come into effect in a later generation, leading to higher exploration.
This should also hold for the unused input genes of nodes, thus it would make sense to allow that, in my opinion.
