### ISSUE TITLE
Why do we print champion.idx in `print_progress`?

### ISSUE THREAD

**Issue by jakobj** [jakobj/python-gp#38]
This does not seem to provide any relevant information to the user or am I wrong? It would be cool to print how many times the objective has been called, but i don't think it's this number?! @mschmidt87

**Comment by mschmidt87** [comment]
I can only imagine that this was written that way to let the user know when the champion has changed?
But I didn't write this code, so I don't know. I agree it doesn't seem to provide useful information.

**Comment by jakobj** [comment]
ok, will remove.
